# facilitar chamada do docker

version: "2.1"
services:
  live-reload:
    image: spotify-radio
    build: .
    environment:
      PORT: 3000
    command:
      - npm
      - run
      - live-reload
    volumes:
      # jogar arquivo tipo node_modules
      - .:/spotify-radio
      - node_modules:/spotify-radio/node_modules
    ports:
      - 3000:3000

  # //suite de teste completa
  test:
    image: spotify-radio
    build: .
    command:
      - npm
      - run
      - test
    volumes:
      # jogar arquivo tipo node_modules
      - .:/spotify-radio
      - node_modules:/spotify-radio/node_modules

  test-watch:
    image: spotify-radio
    build: .
    command:
      - npm
      - run
      - test:watch
    volumes:
      # jogar arquivo tipo node_modules
      - .:/spotify-radio
      - node_modules:/spotify-radio/node_modules

  test-coverage:
    image: spotify-radio
    build: .
    command:
      - npm
      - run
      - test:coverage
    volumes:
      # jogar arquivo tipo node_modules
      - .:/spotify-radio
      - node_modules:/spotify-radio/node_modules

volumes:
  node_modules: {}
